### PR TITLE
Allow to reuse mounted volume

### PR DESCRIPTION
**Pull request by kvaps**
fixes: #34

### CODE REVIEW

**Comment by kvaps** [comment]
Image for test: `docker.io/kvaps/linstor-csi:fix-34`
* Multimount volume is working fine
* Disconnected volume check is also working fine:

```
# drbdadm status pvc-0a816619-d80a-4147-8110-dc0484e2bde1
pvc-0a816619-d80a-4147-8110-dc0484e2bde1 role:Secondary
  disk:Diskless
  m1c5 connection:Connecting
  m1c7 connection:Connecting

```

```
Warning  FailedMount  2s (x3 over 9s)  kubelet, m1c9  MountVolume.SetUp failed for volume "pvc-0a816619-d80a-4147-8110-dc0484e2bde1" : rpc error: code = Internal desc = NodePublishVolume failed for pvc-0a816619-d80a-4147-8110-dc0484e2bde1: checking for exclusive open failed: wrong medium type
```

**Comment by kvaps** [comment]
AttachVolume.Attach failed for volume "pvc-0a816619-d80a-4147-8110-dc0484e2bde1" : rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by kvaps** [comment]
Hi, could we perform release with this change please?

**Comment by vitobotta** [comment]
I should have searched better before posting https://github.com/LINBIT/linstor-csi/issues/50

How can I use this change at the moment? Thanks!

**Comment by kvaps** [comment]
Hi @vitobotta, you can use my docker image `docker.io/kvaps/linstor-csi:fix-34` with this fix included, until LINBIT prepare new release for csi-driver.

**Comment by vitobotta** [comment]
Hi @kvaps ! I was thinking just that. Which deployment should have that image? I see Linstor has several things installed

**Comment by kvaps** [comment]
@vitobotta just do the

```bash
sed -i 's|quay.io/linbit/linstor-csi:v[0-9.]\+|docker.io/kvaps/linstor-csi:fix-34|' your-deployment.yaml
```

And then `kubectl apply` ;)

**Comment by vitobotta** [comment]
@kvaps You're awesome, it works! :D 

Out of curiosity, how has your experience with this CSI driver and Linstor in general been so far? How long have you used it for and with what kind of workloads? Thanks!

**Comment by kvaps** [comment]
Well, we have quite big installation.

I'm not sure that github issues is good place for share my experience.
You can contact me directly over [telegram](t.me/kvaps), [slack](https://kubernetes.slack.com/team/U6RT1EE4S) or [email](mailto:kvapss@gmail.com) if you want to 🙂

**Comment by vitobotta** [comment]
Cool, thanks!

**Comment by rck** [comment]
@kvaps: sure, I will craft a release soon. Currently I maintain the driver and have been on vacation. I will check if there are any other PRs I want to queue up for a release, but expect one soon.

**Comment by rck** [comment]
@kvaps If you can, you could test `rck81/linstor-csi:v0.7.3`. This is what is in the `bv0.7.3` branch and what would be in the next release. Thanks

**Comment by kvaps** [comment]
@rck ok, I've put it into staging, I'll give you feedback after few days

**Comment by kvaps** [comment]
@rck, I've not tested snapshots but the rest it seems is working fine

**Comment by rck** [comment]
Thanks, good enough. It does not contain too many code changes anyways. It is more about updating the tools/k8s versions to latest bugfix versions and crafting an actual release. Still, no need to ruin someones weekend, I will do the release early next week.

**Pull request merged**
